using System;

namespace FDMS.DAL
{
    /// <summary>
    /// Simple object representing Telemetry data for an aircraft. Used for
    /// transferring Telemetry information into and out of a database. One if
    /// constructors is for use by the FdmsDatabase and another is for use by
    /// client code
    /// </summary>
    public class TelemetryRecordDAL
    {
        public string AircraftTailNum;
        public DateTime Timestamp; // Time that the Telemetry data was generated by the aicraft
        public DateTime EntryTimestamp; // Time at which the Telemetry data was inserted into the FDMS database
        public float Accel_X;
        public float Accel_Y;
        public float Accel_Z;
        public float Weight;
        public float Altitude;
        public float Pitch;
        public float Bank;

        public TelemetryRecordDAL() { }

        /// <summary>
        /// Client code constructor for TelemetryRecordDAL. Lacks an EntryTimestamp parameter.
        /// </summary>
        public TelemetryRecordDAL(string aircraftTailNum, DateTime timestamp, float accel_X, float accel_Y, float accel_Z, float weight, float altitude, float pitch, float bank)
        {
            AircraftTailNum = aircraftTailNum;
            Timestamp = timestamp;
            Accel_X = accel_X;
            Accel_Y = accel_Y;
            Accel_Z = accel_Z;
            Weight = weight;
            Altitude = altitude;
            Pitch = pitch;
            Bank = bank;
        }

        /// <summary>
        /// Database constructor for TelemetryRecordDAL. 
        /// </summary>
        public TelemetryRecordDAL(string aircraftTailNum, DateTime timestamp, DateTime entryTimestamp, float accel_X, float accel_Y, float accel_Z, float weight, float altitude, float pitch, float bank)
        {
            AircraftTailNum = aircraftTailNum;
            Timestamp = timestamp;
            EntryTimestamp = entryTimestamp;
            Accel_X = accel_X;
            Accel_Y = accel_Y;
            Accel_Z = accel_Z;
            Weight = weight;
            Altitude = altitude;
            Pitch = pitch;
            Bank = bank;
        }
    }
}
